### ISSUE TITLE
php artisan db:seed error

### ISSUE THREAD

**Issue by sickcity** [hoadv/employee-mgmt-laravel5.4-adminlte#6]
when i try to execute the code php artisan db:seed it gives me these errors:
 [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: insert into `users` (`username`, `email`, `password`, `lastname`, `firstname`, `remember_token`, `updated_at
  `, `created_at`) values (admin, admin@gmail.com, $2y$10$XuU3jo.4m5ZePqM9S6d8u.CfSmyXLwNLrNoFcLzHtnS./Ksf78rB2, Mr,
  admin, qZsLqjAmnt, 2017-08-18 14:51:52, 2017-08-18 14:51:52))

  [PDOException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

**Comment by hoadv** [comment]
Please check your server connection, it is not the coding error. See some answers as bellow:
https://stackoverflow.com/questions/22523298/error-sqlstatehy000-2002-no-connection-could-be-made-because-the-target-mac
https://stackoverflow.com/questions/25609491/php-sqlstatehy000-2002-no-connection-could-be-made-because-the-target-machi
